export interface TimelineItem {
  id: string;
  title: string;
  isDeliverable: boolean;
  hasTemplate: boolean;
  description?: string;
  responsibleRole?: string;
  inputs?: string[];
  outputs?: string[];
}

export interface KeyMeetingTask {
  title: string;
  type: 'meeting' | 'task';
}

export interface TimelinePhase {
  id: string;
  title: string;
  color: string;
  items: TimelineItem[];
  keyMeetingsAndTasks?: KeyMeetingTask[];
  gateReview?: {
    title: string;
    description: string;
  };
}

export const executionTimelineData: TimelinePhase[] = [
  {
    id: "discovery-plan",
    title: "Discovery / Plan",
    color: "bg-blue-500",
    items: [
      {
        id: "initial-sow-discovery",
        title: "Initial SOW for Discovery",
        isDeliverable: false,
        hasTemplate: true,
        description: "The Initial Statement of Work for Discovery outlines the scope, objectives, and deliverables for the discovery phase of the project.",
        responsibleRole: "Project Manager / Account Manager",
        inputs: ["Customer requirements", "Business case", "Initial discussions"],
        outputs: ["Signed SOW for Discovery phase", "Agreed timeline", "Resource allocation"],
      },
      {
        id: "wbs-poap",
        title: "WBS POAP",
        isDeliverable: true,
        hasTemplate: true,
        description: "Work Breakdown Structure and Plan on a Page - A high-level project plan showing key milestones, deliverables, and timeline.",
        responsibleRole: "Project Manager",
        inputs: ["SOW", "Customer requirements", "Resource availability"],
        outputs: ["Visual project plan", "Milestone schedule", "Dependencies map"],
      },
      {
        id: "questionnaire",
        title: "Questionnaire",
        isDeliverable: true,
        hasTemplate: true,
        description: "A comprehensive questionnaire to gather detailed requirements and information from the customer.",
        responsibleRole: "Business Analyst / Solution Architect",
        inputs: ["Initial SOW", "Customer contacts", "Business requirements"],
        outputs: ["Completed questionnaire", "Requirement clarifications", "Gap analysis"],
      },
      {
        id: "deliverable-definition",
        title: "Deliverable Definition",
        isDeliverable: false,
        hasTemplate: true,
        description: "Defines the specific deliverables for the project including acceptance criteria and delivery schedule.",
        responsibleRole: "Project Manager",
        inputs: ["SOW", "WBS", "Customer requirements"],
        outputs: ["Deliverables list", "Acceptance criteria", "Delivery schedule"],
      },
      {
        id: "sow",
        title: "SOW",
        isDeliverable: false,
        hasTemplate: true,
        description: "The full Statement of Work document outlining complete project scope, deliverables, timeline, and commercial terms.",
        responsibleRole: "Project Manager / Account Manager",
        inputs: ["Discovery findings", "Requirements", "Resource plans", "Commercial terms"],
        outputs: ["Signed SOW", "Project baseline", "Commercial agreement"],
      },
      {
        id: "risks",
        title: "Risks",
        isDeliverable: false,
        hasTemplate: true,
        description: "Initial risk assessment identifying potential project risks and mitigation strategies.",
        responsibleRole: "Project Manager",
        inputs: ["SOW", "Technical assessment", "Customer environment"],
        outputs: ["Risk register", "Mitigation plans", "Risk owners"],
      },
      {
        id: "internal-estimates",
        title: "Internal Estimates",
        isDeliverable: false,
        hasTemplate: true,
        description: "Internal effort and cost estimates for the project delivery.",
        responsibleRole: "Project Manager / Technical Lead",
        inputs: ["SOW", "WBS", "Resource rates", "Historical data"],
        outputs: ["Effort estimates", "Cost breakdown", "Resource plan"],
      },
      {
        id: "risk-log",
        title: "Risk Log",
        isDeliverable: false,
        hasTemplate: true,
        description: "Ongoing log to track and manage project risks throughout the project lifecycle.",
        responsibleRole: "Project Manager",
        inputs: ["Initial risks", "Project changes", "Issue logs"],
        outputs: ["Updated risk register", "Risk status reports", "Escalations"],
      },
      {
        id: "solution-outline",
        title: "Solution Outline",
        isDeliverable: true,
        hasTemplate: true,
        description: "High-level solution architecture and approach document.",
        responsibleRole: "Solution Architect",
        inputs: ["Requirements", "Technical constraints", "Integration points"],
        outputs: ["Solution overview", "Architecture diagram", "Technology stack"],
      },
      {
        id: "requirements",
        title: "Requirements",
        isDeliverable: true,
        hasTemplate: true,
        description: "Detailed requirements document capturing functional and non-functional requirements.",
        responsibleRole: "Business Analyst",
        inputs: ["Questionnaire responses", "Stakeholder interviews", "Current state analysis"],
        outputs: ["Requirements specification", "Traceability matrix", "Sign-off"],
      },
      {
        id: "detailed-plan",
        title: "Detailed Plan",
        isDeliverable: false,
        hasTemplate: true,
        description: "Comprehensive project plan with detailed tasks, resources, and timeline.",
        responsibleRole: "Project Manager",
        inputs: ["WBS", "Resource allocation", "Dependencies"],
        outputs: ["Detailed project schedule", "Resource assignments", "Critical path"],
      },
    ],
    keyMeetingsAndTasks: [
      { title: "Project Kick-off Call", type: "meeting" },
      { title: "Requirements Gathering Workshop", type: "meeting" },
      { title: "Stakeholder Alignment Session", type: "meeting" },
      { title: "Complete Discovery Questionnaire", type: "task" },
      { title: "Define Project Scope Document", type: "task" },
    ],
    gateReview: {
      title: "Gate 1 Review",
      description: "Review and approval checkpoint before proceeding to Prepare/Requirements phase.",
    },
  },
  {
    id: "prepare-requirements",
    title: "Prepare / Requirements",
    color: "bg-violet-500",
    items: [
      {
        id: "development-environment",
        title: "Development Environment",
        isDeliverable: true,
        hasTemplate: true,
        description: "Setup and configuration documentation for the development environment.",
        responsibleRole: "Technical Lead / DevOps",
        inputs: ["Infrastructure requirements", "Security policies", "Tool requirements"],
        outputs: ["Environment specification", "Access credentials", "Setup guide"],
      },
      {
        id: "data",
        title: "Data",
        isDeliverable: false,
        hasTemplate: true,
        description: "Data requirements and data handling procedures documentation.",
        responsibleRole: "Data Architect / Technical Lead",
        inputs: ["Data sources", "Data models", "Privacy requirements"],
        outputs: ["Data dictionary", "Data flow diagrams", "Handling procedures"],
      },
      {
        id: "test-plan-initial",
        title: "Test Plan",
        isDeliverable: false,
        hasTemplate: true,
        description: "Initial test planning document outlining testing approach and strategy.",
        responsibleRole: "Test Lead",
        inputs: ["Requirements", "Solution design", "Quality standards"],
        outputs: ["Test strategy", "Test approach", "Resource needs"],
      },
      {
        id: "access",
        title: "Access",
        isDeliverable: false,
        hasTemplate: true,
        description: "Access requirements and permissions documentation for all project systems.",
        responsibleRole: "Project Manager / Security Lead",
        inputs: ["Team roster", "System list", "Security policies"],
        outputs: ["Access matrix", "Permission requests", "Onboarding checklist"],
      },
      {
        id: "support-model",
        title: "Support Model",
        isDeliverable: false,
        hasTemplate: true,
        description: "Defines the support structure and escalation procedures for the project.",
        responsibleRole: "Project Manager / Service Delivery Manager",
        inputs: ["SLA requirements", "Team structure", "Customer expectations"],
        outputs: ["Support structure", "Escalation matrix", "Contact list"],
      },
      {
        id: "test-plan-deliverable",
        title: "Test Plan",
        isDeliverable: true,
        hasTemplate: true,
        description: "Comprehensive test plan document with detailed test cases and acceptance criteria.",
        responsibleRole: "Test Lead",
        inputs: ["Requirements", "Design documents", "Acceptance criteria"],
        outputs: ["Test plan", "Test cases", "Test schedule"],
      },
      {
        id: "licenses",
        title: "Licenses",
        isDeliverable: true,
        hasTemplate: true,
        description: "Software licensing requirements and procurement documentation.",
        responsibleRole: "Project Manager / Commercial Lead",
        inputs: ["Software requirements", "User counts", "Commercial terms"],
        outputs: ["License inventory", "Procurement plan", "Cost breakdown"],
      },
      {
        id: "cut-over-plan",
        title: "Cut Over Plan",
        isDeliverable: true,
        hasTemplate: true,
        description: "Plan for transitioning from old system to new system including rollback procedures.",
        responsibleRole: "Project Manager / Technical Lead",
        inputs: ["Go-live requirements", "Risk assessment", "Stakeholder availability"],
        outputs: ["Cut-over schedule", "Rollback plan", "Communication plan"],
      },
      {
        id: "migration-strategy",
        title: "Migration Strategy + Approach",
        isDeliverable: true,
        hasTemplate: true,
        description: "Overall migration strategy and technical approach documentation.",
        responsibleRole: "Solution Architect / Migration Lead",
        inputs: ["Current state", "Target state", "Technical constraints"],
        outputs: ["Migration approach", "Tool selection", "Timeline"],
      },
      {
        id: "kick-off",
        title: "Kick Off",
        isDeliverable: false,
        hasTemplate: true,
        description: "Project kick-off meeting materials and agenda.",
        responsibleRole: "Project Manager",
        inputs: ["Project plan", "Team roster", "Stakeholder list"],
        outputs: ["Kick-off presentation", "Meeting minutes", "Action items"],
      },
      {
        id: "data-profiling",
        title: "Data Profiling",
        isDeliverable: true,
        hasTemplate: true,
        description: "Analysis and profiling of source data for migration.",
        responsibleRole: "Data Analyst / Migration Specialist",
        inputs: ["Source data access", "Data requirements", "Quality standards"],
        outputs: ["Data profile report", "Quality assessment", "Recommendations"],
      },
      {
        id: "data-cleansing-approach",
        title: "Data Cleansing Approach",
        isDeliverable: false,
        hasTemplate: true,
        description: "Strategy and procedures for data cleansing activities.",
        responsibleRole: "Data Analyst / Data Quality Lead",
        inputs: ["Data profile", "Quality requirements", "Business rules"],
        outputs: ["Cleansing rules", "Validation criteria", "Process workflow"],
      },
    ],
    keyMeetingsAndTasks: [
      { title: "Environment Setup Review", type: "meeting" },
      { title: "Data Migration Planning Session", type: "meeting" },
      { title: "Test Strategy Workshop", type: "meeting" },
      { title: "Prepare Access Requests", type: "task" },
      { title: "Define Support Model", type: "task" },
    ],
    gateReview: {
      title: "Gate 2 Review",
      description: "Review and approval checkpoint before proceeding to Explore/Design phase.",
    },
  },
  {
    id: "explore-design",
    title: "Explore / Design",
    color: "bg-purple-500",
    items: [
      {
        id: "high-level-design",
        title: "High Level Design",
        isDeliverable: true,
        hasTemplate: true,
        description: "High-level solution design document covering architecture and major components.",
        responsibleRole: "Solution Architect",
        inputs: ["Requirements", "Solution outline", "Technical constraints"],
        outputs: ["HLD document", "Architecture diagrams", "Component overview"],
      },
      {
        id: "test-scripts",
        title: "Test Scripts",
        isDeliverable: true,
        hasTemplate: true,
        description: "Detailed test scripts for executing test cases.",
        responsibleRole: "Test Lead / QA Engineer",
        inputs: ["Test plan", "Requirements", "Design documents"],
        outputs: ["Test scripts", "Test data", "Expected results"],
      },
      {
        id: "infrastructure-design",
        title: "Infrastructure Design",
        isDeliverable: true,
        hasTemplate: true,
        description: "Infrastructure architecture and specifications.",
        responsibleRole: "Infrastructure Architect / DevOps Lead",
        inputs: ["HLD", "Performance requirements", "Security requirements"],
        outputs: ["Infrastructure diagram", "Sizing specifications", "Network design"],
      },
      {
        id: "tna",
        title: "TNA",
        isDeliverable: true,
        hasTemplate: true,
        description: "Training Needs Analysis to identify training requirements for end users.",
        responsibleRole: "Training Lead / Business Analyst",
        inputs: ["User roles", "System changes", "Skill assessment"],
        outputs: ["Training needs matrix", "Training plan", "Resource requirements"],
      },
      {
        id: "data-mapping",
        title: "Data Mapping",
        isDeliverable: true,
        hasTemplate: true,
        description: "Detailed mapping between source and target data structures.",
        responsibleRole: "Data Architect / Migration Specialist",
        inputs: ["Source data model", "Target data model", "Business rules"],
        outputs: ["Data mapping document", "Transformation rules", "Validation rules"],
      },
    ],
    keyMeetingsAndTasks: [
      { title: "Design Review Workshop", type: "meeting" },
      { title: "Architecture Sign-off Meeting", type: "meeting" },
      { title: "Training Needs Analysis Session", type: "meeting" },
      { title: "Complete Data Mapping", type: "task" },
      { title: "Finalize Test Scripts", type: "task" },
    ],
    gateReview: {
      title: "Gate 3 Review",
      description: "Review and approval checkpoint before proceeding to Realise/Implementation phase.",
    },
  },
  {
    id: "realise-implementation",
    title: "Realise / Implementation",
    color: "bg-orange-500",
    items: [
      {
        id: "low-level-design",
        title: "Low Level Design",
        isDeliverable: true,
        hasTemplate: true,
        description: "Detailed technical design document with implementation specifics.",
        responsibleRole: "Technical Lead / Developer",
        inputs: ["HLD", "Requirements", "Standards"],
        outputs: ["LLD document", "Technical specifications", "Interface designs"],
      },
      {
        id: "build-configuration",
        title: "Build Configuration",
        isDeliverable: true,
        hasTemplate: true,
        description: "Build and configuration documentation for the solution.",
        responsibleRole: "Developer / Configuration Specialist",
        inputs: ["LLD", "Environment specs", "Standards"],
        outputs: ["Configuration guide", "Build scripts", "Settings documentation"],
      },
      {
        id: "admin-guide",
        title: "Admin Guide",
        isDeliverable: true,
        hasTemplate: true,
        description: "System administration guide for ongoing maintenance.",
        responsibleRole: "Technical Lead / Technical Writer",
        inputs: ["System design", "Operations requirements", "Support model"],
        outputs: ["Admin documentation", "Maintenance procedures", "Troubleshooting guide"],
      },
      {
        id: "user-guide-training",
        title: "User Guide / Training",
        isDeliverable: true,
        hasTemplate: true,
        description: "End user documentation and training materials.",
        responsibleRole: "Training Lead / Technical Writer",
        inputs: ["TNA", "System functionality", "User roles"],
        outputs: ["User guide", "Training materials", "Quick reference cards"],
      },
      {
        id: "deployment-guide",
        title: "Deployment Guide",
        isDeliverable: true,
        hasTemplate: true,
        description: "Step-by-step deployment instructions for the solution.",
        responsibleRole: "DevOps / Technical Lead",
        inputs: ["Build configuration", "Infrastructure design", "Cut-over plan"],
        outputs: ["Deployment steps", "Verification checklist", "Rollback procedures"],
      },
      {
        id: "process-delivery",
        title: "Process Delivery",
        isDeliverable: false,
        hasTemplate: true,
        description: "Documentation of business process changes and implementations.",
        responsibleRole: "Business Analyst / Process Lead",
        inputs: ["Requirements", "Current processes", "Target processes"],
        outputs: ["Process documentation", "Change impact", "Adoption plan"],
      },
      {
        id: "unit-link-testing",
        title: "Unit / Link Testing",
        isDeliverable: false,
        hasTemplate: true,
        description: "Unit and integration testing documentation and results.",
        responsibleRole: "Developer / Test Lead",
        inputs: ["LLD", "Test plan", "Build configuration"],
        outputs: ["Test results", "Defect log", "Coverage report"],
      },
      {
        id: "change-release-notice",
        title: "Change Notice / Release Notice",
        isDeliverable: true,
        hasTemplate: true,
        description: "Formal change and release notification documentation.",
        responsibleRole: "Project Manager / Release Manager",
        inputs: ["Deployment guide", "Test results", "Stakeholder list"],
        outputs: ["Change notice", "Release notes", "Approval sign-off"],
      },
    ],
    keyMeetingsAndTasks: [
      { title: "Sprint Planning Sessions", type: "meeting" },
      { title: "Weekly Build Review", type: "meeting" },
      { title: "UAT Readiness Meeting", type: "meeting" },
      { title: "Complete Unit Testing", type: "task" },
      { title: "Prepare Release Documentation", type: "task" },
    ],
    gateReview: {
      title: "Gate 4 Review",
      description: "Review and approval checkpoint before proceeding to Deploy/Exit phase.",
    },
  },
  {
    id: "deploy-exit",
    title: "Deploy / Exit",
    color: "bg-emerald-500",
    items: [
      {
        id: "batch-load-migration",
        title: "Batch Load per Migration",
        isDeliverable: true,
        hasTemplate: true,
        description: "Batch data loading documentation and results for each migration run (if eQ runs the migration).",
        responsibleRole: "Migration Specialist / Data Lead",
        inputs: ["Data mapping", "Migration strategy", "Source data"],
        outputs: ["Load results", "Validation report", "Error log"],
      },
      {
        id: "validation",
        title: "Validation",
        isDeliverable: true,
        hasTemplate: true,
        description: "Post-migration validation documentation and sign-off.",
        responsibleRole: "Test Lead / Business Analyst",
        inputs: ["Test plan", "Acceptance criteria", "Migration results"],
        outputs: ["Validation results", "Sign-off document", "Issue list"],
      },
      {
        id: "customer-plan",
        title: "Customer Plan",
        isDeliverable: true,
        hasTemplate: true,
        description: "Customer-facing project plan and timeline.",
        responsibleRole: "Project Manager",
        inputs: ["Internal plan", "Customer requirements", "Milestones"],
        outputs: ["Customer plan", "Status report template", "Communication schedule"],
      },
      {
        id: "els",
        title: "ELS",
        isDeliverable: true,
        hasTemplate: true,
        description: "Early Life Support documentation and procedures.",
        responsibleRole: "Service Delivery Manager / Project Manager",
        inputs: ["Support model", "Go-live plan", "Escalation matrix"],
        outputs: ["ELS plan", "Support schedule", "Handover checklist"],
      },
      {
        id: "perform-training",
        title: "Perform Training",
        isDeliverable: true,
        hasTemplate: true,
        description: "Training delivery documentation and attendance records.",
        responsibleRole: "Training Lead",
        inputs: ["Training materials", "User list", "Schedule"],
        outputs: ["Training records", "Attendance log", "Feedback forms"],
      },
      {
        id: "exit-plan",
        title: "Exit Plan",
        isDeliverable: true,
        hasTemplate: true,
        description: "Project closure and handover plan.",
        responsibleRole: "Project Manager",
        inputs: ["Deliverables checklist", "Lessons learned", "Handover requirements"],
        outputs: ["Exit plan", "Closure report", "Handover documentation"],
      },
    ],
    keyMeetingsAndTasks: [
      { title: "Go-Live Readiness Review", type: "meeting" },
      { title: "Hypercare Daily Stand-ups", type: "meeting" },
      { title: "Project Closure Meeting", type: "meeting" },
      { title: "Complete Knowledge Transfer", type: "task" },
      { title: "Finalize Project Documentation", type: "task" },
    ],
    gateReview: {
      title: "Gate 5 Review",
      description: "Final review and project closure approval.",
    },
  },
];
