
-- Seed Migration Method lifecycle items
INSERT INTO public.lifecycle_items (method_slug, phase_id, title, description, is_deliverable, has_template, responsible_role, inputs, outputs, order_index) VALUES
-- Discovery / Plan
('migration', 'discovery-plan', 'Initial SOW for Discovery', 'The Initial Statement of Work for Discovery outlines the scope, objectives, and deliverables for the discovery phase of the project.', false, true, 'Project Manager / Account Manager', '{"Customer requirements","Business case","Initial discussions"}', '{"Signed SOW for Discovery phase","Agreed timeline","Resource allocation"}', 0),
('migration', 'discovery-plan', 'WBS POAP', 'Work Breakdown Structure and Plan on a Page - A high-level project plan showing key milestones, deliverables, and timeline.', true, true, 'Project Manager', '{"SOW","Customer requirements","Resource availability"}', '{"Visual project plan","Milestone schedule","Dependencies map"}', 1),
('migration', 'discovery-plan', 'Questionnaire', 'A comprehensive questionnaire to gather detailed requirements and information from the customer.', true, true, 'Business Analyst / Solution Architect', '{"Initial SOW","Customer contacts","Business requirements"}', '{"Completed questionnaire","Requirement clarifications","Gap analysis"}', 2),
('migration', 'discovery-plan', 'Deliverable Definition', 'Defines the specific deliverables for the project including acceptance criteria and delivery schedule.', false, true, 'Project Manager', '{"SOW","WBS","Customer requirements"}', '{"Deliverables list","Acceptance criteria","Delivery schedule"}', 3),
('migration', 'discovery-plan', 'SOW', 'The full Statement of Work document outlining complete project scope, deliverables, timeline, and commercial terms.', false, true, 'Project Manager / Account Manager', '{"Discovery findings","Requirements","Resource plans","Commercial terms"}', '{"Signed SOW","Project baseline","Commercial agreement"}', 4),
('migration', 'discovery-plan', 'Risks', 'Initial risk assessment identifying potential project risks and mitigation strategies.', false, true, 'Project Manager', '{"SOW","Technical assessment","Customer environment"}', '{"Risk register","Mitigation plans","Risk owners"}', 5),
('migration', 'discovery-plan', 'Internal Estimates', 'Internal effort and cost estimates for the project delivery.', false, true, 'Project Manager / Technical Lead', '{"SOW","WBS","Resource rates","Historical data"}', '{"Effort estimates","Cost breakdown","Resource plan"}', 6),
('migration', 'discovery-plan', 'Risk Log', 'Ongoing log to track and manage project risks throughout the project lifecycle.', false, true, 'Project Manager', '{"Initial risks","Project changes","Issue logs"}', '{"Updated risk register","Risk status reports","Escalations"}', 7),
('migration', 'discovery-plan', 'Solution Outline', 'High-level solution architecture and approach document.', true, true, 'Solution Architect', '{"Requirements","Technical constraints","Integration points"}', '{"Solution overview","Architecture diagram","Technology stack"}', 8),
('migration', 'discovery-plan', 'Requirements', 'Detailed requirements document capturing functional and non-functional requirements.', true, true, 'Business Analyst', '{"Questionnaire responses","Stakeholder interviews","Current state analysis"}', '{"Requirements specification","Traceability matrix","Sign-off"}', 9),
('migration', 'discovery-plan', 'Detailed Plan', 'Comprehensive project plan with detailed tasks, resources, and timeline.', false, true, 'Project Manager', '{"WBS","Resource allocation","Dependencies"}', '{"Detailed project schedule","Resource assignments","Critical path"}', 10),
-- Prepare / Requirements
('migration', 'prepare-requirements', 'Development Environment', 'Setup and configuration documentation for the development environment.', true, true, 'Technical Lead / DevOps', '{"Infrastructure requirements","Security policies","Tool requirements"}', '{"Environment specification","Access credentials","Setup guide"}', 0),
('migration', 'prepare-requirements', 'Data', 'Data requirements and data handling procedures documentation.', false, true, 'Data Architect / Technical Lead', '{"Data sources","Data models","Privacy requirements"}', '{"Data dictionary","Data flow diagrams","Handling procedures"}', 1),
('migration', 'prepare-requirements', 'Test Plan', 'Initial test planning document outlining testing approach and strategy.', false, true, 'Test Lead', '{"Requirements","Solution design","Quality standards"}', '{"Test strategy","Test approach","Resource needs"}', 2),
('migration', 'prepare-requirements', 'Access', 'Access requirements and permissions documentation for all project systems.', false, true, 'Project Manager / Security Lead', '{"Team roster","System list","Security policies"}', '{"Access matrix","Permission requests","Onboarding checklist"}', 3),
('migration', 'prepare-requirements', 'Support Model', 'Defines the support structure and escalation procedures for the project.', false, true, 'Project Manager / Service Delivery Manager', '{"SLA requirements","Team structure","Customer expectations"}', '{"Support structure","Escalation matrix","Contact list"}', 4),
('migration', 'prepare-requirements', 'Test Plan (Deliverable)', 'Comprehensive test plan document with detailed test cases and acceptance criteria.', true, true, 'Test Lead', '{"Requirements","Design documents","Acceptance criteria"}', '{"Test plan","Test cases","Test schedule"}', 5),
('migration', 'prepare-requirements', 'Licenses', 'Software licensing requirements and procurement documentation.', true, true, 'Project Manager / Commercial Lead', '{"Software requirements","User counts","Commercial terms"}', '{"License inventory","Procurement plan","Cost breakdown"}', 6),
('migration', 'prepare-requirements', 'Cut Over Plan', 'Plan for transitioning from old system to new system including rollback procedures.', true, true, 'Project Manager / Technical Lead', '{"Go-live requirements","Risk assessment","Stakeholder availability"}', '{"Cut-over schedule","Rollback plan","Communication plan"}', 7),
('migration', 'prepare-requirements', 'Migration Strategy + Approach', 'Overall migration strategy and technical approach documentation.', true, true, 'Solution Architect / Migration Lead', '{"Current state","Target state","Technical constraints"}', '{"Migration approach","Tool selection","Timeline"}', 8),
('migration', 'prepare-requirements', 'Kick Off', 'Project kick-off meeting materials and agenda.', false, true, 'Project Manager', '{"Project plan","Team roster","Stakeholder list"}', '{"Kick-off presentation","Meeting minutes","Action items"}', 9),
('migration', 'prepare-requirements', 'Data Profiling', 'Analysis and profiling of source data for migration.', true, true, 'Data Analyst / Migration Specialist', '{"Source data access","Data requirements","Quality standards"}', '{"Data profile report","Quality assessment","Recommendations"}', 10),
('migration', 'prepare-requirements', 'Data Cleansing Approach', 'Strategy and procedures for data cleansing activities.', false, true, 'Data Analyst / Data Quality Lead', '{"Data profile","Quality requirements","Business rules"}', '{"Cleansing rules","Validation criteria","Process workflow"}', 11),
-- Explore / Design
('migration', 'explore-design', 'High Level Design', 'High-level solution design document covering architecture and major components.', true, true, 'Solution Architect', '{"Requirements","Solution outline","Technical constraints"}', '{"HLD document","Architecture diagrams","Component overview"}', 0),
('migration', 'explore-design', 'Test Scripts', 'Detailed test scripts for executing test cases.', true, true, 'Test Lead / QA Engineer', '{"Test plan","Requirements","Design documents"}', '{"Test scripts","Test data","Expected results"}', 1),
('migration', 'explore-design', 'Infrastructure Design', 'Infrastructure architecture and specifications.', true, true, 'Infrastructure Architect / DevOps Lead', '{"HLD","Performance requirements","Security requirements"}', '{"Infrastructure diagram","Sizing specifications","Network design"}', 2),
('migration', 'explore-design', 'TNA', 'Training Needs Analysis to identify training requirements for end users.', true, true, 'Training Lead / Business Analyst', '{"User roles","System changes","Skill assessment"}', '{"Training needs matrix","Training plan","Resource requirements"}', 3),
('migration', 'explore-design', 'Data Mapping', 'Detailed mapping between source and target data structures.', true, true, 'Data Architect / Migration Specialist', '{"Source data model","Target data model","Business rules"}', '{"Data mapping document","Transformation rules","Validation rules"}', 4),
-- Realise / Implementation
('migration', 'realise-implementation', 'Low Level Design', 'Detailed technical design document with implementation specifics.', true, true, 'Technical Lead / Developer', '{"HLD","Requirements","Standards"}', '{"LLD document","Technical specifications","Interface designs"}', 0),
('migration', 'realise-implementation', 'Build Configuration', 'Build and configuration documentation for the solution.', true, true, 'Developer / Configuration Specialist', '{"LLD","Environment specs","Standards"}', '{"Configuration guide","Build scripts","Settings documentation"}', 1),
('migration', 'realise-implementation', 'Admin Guide', 'System administration guide for ongoing maintenance.', true, true, 'Technical Lead / Technical Writer', '{"System design","Operations requirements","Support model"}', '{"Admin documentation","Maintenance procedures","Troubleshooting guide"}', 2),
('migration', 'realise-implementation', 'User Guide / Training', 'End user documentation and training materials.', true, true, 'Training Lead / Technical Writer', '{"TNA","System functionality","User roles"}', '{"User guide","Training materials","Quick reference cards"}', 3),
('migration', 'realise-implementation', 'Deployment Guide', 'Step-by-step deployment instructions for the solution.', true, true, 'DevOps / Technical Lead', '{"Build configuration","Infrastructure design","Cut-over plan"}', '{"Deployment steps","Verification checklist","Rollback procedures"}', 4),
('migration', 'realise-implementation', 'Process Delivery', 'Documentation of business process changes and implementations.', false, true, 'Business Analyst / Process Lead', '{"Requirements","Current processes","Target processes"}', '{"Process documentation","Change impact","Adoption plan"}', 5),
('migration', 'realise-implementation', 'Unit / Link Testing', 'Unit and integration testing documentation and results.', false, true, 'Developer / Test Lead', '{"LLD","Test plan","Build configuration"}', '{"Test results","Defect log","Coverage report"}', 6),
('migration', 'realise-implementation', 'Change Notice / Release Notice', 'Formal change and release notification documentation.', true, true, 'Project Manager / Release Manager', '{"Deployment guide","Test results","Stakeholder list"}', '{"Change notice","Release notes","Approval sign-off"}', 7),
-- Deploy / Exit
('migration', 'deploy-exit', 'Batch Load per Migration', 'Batch data loading documentation and results for each migration run.', true, true, 'Migration Specialist / Data Lead', '{"Data mapping","Migration strategy","Source data"}', '{"Load results","Validation report","Error log"}', 0),
('migration', 'deploy-exit', 'Validation', 'Post-migration validation documentation and sign-off.', true, true, 'Test Lead / Business Analyst', '{"Test plan","Acceptance criteria","Migration results"}', '{"Validation results","Sign-off document","Issue list"}', 1),
('migration', 'deploy-exit', 'Customer Plan', 'Customer-facing project plan and timeline.', true, true, 'Project Manager', '{"Internal plan","Customer requirements","Milestones"}', '{"Customer plan","Status report template","Communication schedule"}', 2),
('migration', 'deploy-exit', 'ELS', 'Early Life Support documentation and procedures.', true, true, 'Service Delivery Manager / Project Manager', '{"Support model","Go-live plan","Escalation matrix"}', '{"ELS plan","Support schedule","Handover checklist"}', 3),
('migration', 'deploy-exit', 'Perform Training', 'Training delivery documentation and attendance records.', true, true, 'Training Lead', '{"Training materials","User list","Schedule"}', '{"Training records","Attendance log","Feedback forms"}', 4),
('migration', 'deploy-exit', 'Exit Plan', 'Project closure and handover plan.', true, true, 'Project Manager', '{"Deliverables checklist","Lessons learned","Handover requirements"}', '{"Exit plan","Closure report","Handover documentation"}', 5);

-- Seed Migration Method meetings and tasks
INSERT INTO public.lifecycle_meetings_tasks (method_slug, phase_id, title, type, order_index) VALUES
('migration', 'discovery-plan', 'Project Kick-off Call', 'meeting', 0),
('migration', 'discovery-plan', 'Requirements Gathering Workshop', 'meeting', 1),
('migration', 'discovery-plan', 'Stakeholder Alignment Session', 'meeting', 2),
('migration', 'discovery-plan', 'Complete Discovery Questionnaire', 'task', 3),
('migration', 'discovery-plan', 'Define Project Scope Document', 'task', 4),
('migration', 'prepare-requirements', 'Environment Setup Review', 'meeting', 0),
('migration', 'prepare-requirements', 'Data Migration Planning Session', 'meeting', 1),
('migration', 'prepare-requirements', 'Test Strategy Workshop', 'meeting', 2),
('migration', 'prepare-requirements', 'Prepare Access Requests', 'task', 3),
('migration', 'prepare-requirements', 'Define Support Model', 'task', 4),
('migration', 'explore-design', 'Design Review Workshop', 'meeting', 0),
('migration', 'explore-design', 'Architecture Sign-off Meeting', 'meeting', 1),
('migration', 'explore-design', 'Training Needs Analysis Session', 'meeting', 2),
('migration', 'explore-design', 'Complete Data Mapping', 'task', 3),
('migration', 'explore-design', 'Finalize Test Scripts', 'task', 4),
('migration', 'realise-implementation', 'Sprint Planning Sessions', 'meeting', 0),
('migration', 'realise-implementation', 'Weekly Build Review', 'meeting', 1),
('migration', 'realise-implementation', 'UAT Readiness Meeting', 'meeting', 2),
('migration', 'realise-implementation', 'Complete Unit Testing', 'task', 3),
('migration', 'realise-implementation', 'Prepare Release Documentation', 'task', 4),
('migration', 'deploy-exit', 'Go-Live Readiness Review', 'meeting', 0),
('migration', 'deploy-exit', 'Hypercare Daily Stand-ups', 'meeting', 1),
('migration', 'deploy-exit', 'Project Closure Meeting', 'meeting', 2),
('migration', 'deploy-exit', 'Complete Knowledge Transfer', 'task', 3),
('migration', 'deploy-exit', 'Finalize Project Documentation', 'task', 4);
